@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Component Diagram for D-Apps component
Person(customer, "Neko Wallet User", "Users using Neko Wallet application (mobile devices)")
System_Boundary(system, "Neko Wallet System") {
    Container(mobile, "Mobile App", "JavaScript: React Native", "Provides accessibility to application's major services to general users")
    Rel_R(customer, mobile, "uses")
    Boundary(api, "API Application", "Typescript: NodeJS, Express") {
        Component(dAppController, "DAppController", "Controller", "Receives GET queries to retrieve d-app information")
        Component(dAppBannerController, "DAppBannerController", "Controller", "Receives GET queries to retrieve d-app banner information")
        Component(dAppCategoryController, "DAppCategoryController", "Controller", "Receives GET queries to retrieve d-app category information")
        Component(dAppHistoryController, "DAppHistoryController", "Controller", "Receives GET queries to retrieve d-app history information")
        Component(dAppService, "DAppService", "Service", "Receives queries' params, manipulate data retrieved from DB")
        Component(dAppBannerService, "DAppBannerService", "Service", "Receives queries' params, manipulate data retrieved from DB")
        Component(dAppCategoryService, "DAppCategoryService", "Service", "Receives queries' params, manipulate data retrieved from DB")
        Component(dAppHistoryService, "DAppHistoryService", "Service", "Receives queries' params, manipulate data retrieved from DB")
        Component(dAppValidator, "DAppValidator", "Validator", "Validate queries params passed into d-app APIs")
        Component(dAppBannerValidator, "DAppBannerValidator", "Validator", "Validate queries params passed into d-app banner APIs")
        Component(dAppCategoryValidator, "DAppCategoryValidator", "Validator", "Validate queries params passed into d-app category APIs")
        Component(dAppHistoryValidator, "DAppHistoryValidator", "Validator", "Validate queries params passed into d-app history APIs")
        Component(dAppRepo, "DAppRepository", "Repository", "Retrieves d-apps' data from cryptocurrency database")
        Component(dAppMappingRepo, "DAppMappingRepository", "Repository", "Retrieves d-app mappings information from cryptocurrency database")
        Component(dAppBannerRepo, "DAppBannerRepository", "Repository", "Retrieves d-app banners information from cryptocurrency database")
        Component(dAppCategoryRepo, "DAppCategoryRepository", "Repository", "Retrieves d-app categories information from cryptocurrency database")
        Component(dAppHistoryRepo, "DAppHistoryRepository", "Repository", "Retrieves d-app histories information from cryptocurrency database")
    }
    ComponentDb(cryptoDB, "CryptoDatabase", "PostgreSQL Database", "Cryptocurrency related database")
    Lay_U(dAppController, dAppBannerController)
    Lay_U(dAppBannerController, dAppCategoryController)
    Lay_U(dAppService, dAppBannerService)
    Lay_U(dAppService, dAppHistoryService)
    Lay_D(dAppRepo, dAppMappingRepo)
    Rel(mobile, api, "makes API calls", "JSON/HTTPS")
    Rel_R(dAppBannerController, dAppBannerService, "uses")
    Rel_R(dAppController, dAppService, "uses")
    Rel_R(dAppCategoryController, dAppCategoryService, "uses")
    Rel_R(dAppHistoryController, dAppHistoryService, "uses")
    Rel_U(dAppBannerController, dAppBannerValidator, "uses")
    Rel_D(dAppController, dAppValidator, "uses")
    Rel_U(dAppCategoryController, dAppCategoryValidator, "uses")
    Rel_D(dAppHistoryController, dAppHistoryValidator, "uses")
    Rel_R(dAppService, dAppRepo, "uses")
    Rel_R(dAppService, dAppMappingRepo, "uses")
    Rel_R(dAppCategoryService, dAppCategoryRepo, "uses")
    Rel_R(dAppHistoryService, dAppHistoryRepo, "uses")
    Rel_R(dAppBannerService, dAppBannerRepo, "uses")
    Rel_R(dAppRepo, cryptoDB, "reads/writes", "ORM: ObjectionJS")
    Rel_R(dAppBannerRepo, cryptoDB, "reads/writes", "ORM: ObjectionJS")
    Rel_R(dAppMappingRepo, cryptoDB, "reads/writes", "ORM: ObjectionJS")
    Rel_R(dAppCategoryRepo, cryptoDB, "reads/writes", "ORM: ObjectionJS")
    Rel_R(dAppHistoryRepo, cryptoDB, "reads/writes", "ORM: ObjectionJS")
}
@enduml
