@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Transaction component
Person(customer, "Neko Wallet User", "Users using Neko Wallet application (mobile devices)")

System_Ext(blockchain, "Blockchain", "Blockchain platforms such as SOL, BSC, ETH,...")
System_Boundary(system, "Neko Wallet System") {
    Container(mobile, "Mobile App", "JavaScript: React Native", "Provides accessibility to application's major services to general users")
    Rel_D(customer, mobile, "uses")
    Container(library, "Blockchain Library", "TypeScript", "provides functionality and communicates with Blockchain platforms")
    Boundary(api, "API Application", "Typescript: NodeJS, Express") {
        Component(swapController, "SwapController", "Controller", "Receives GET queries to retrieve market and cryptocurrency information")
        Component(transactionController, "TransactionController", "Controller", "Receives GET queries to retrieve the latest price information")
        Component(swapService, "SwapService", "Service", "Receives queries' params, manipulate data retrieved from DB")
        Component(transactionService, "TransactionService", "Service", "Receives queries' params, manipulate data retrieved from DB")
        Component(swapValidator, "SwapValidator", "Validator", "Validate queries params passed into swap order APIs")
        Component(transactionValidator, "TransactionValidator", "Validator", "Validate queries params passed into transaction APIs")
        Component(authenMiddleware, "AuthenticationMiddleware", "Middleware", "Validate access token passed along with requests to transaction controller")
        Component(swapRepo, "SwapRepository", "Repository", "Retrieves swap orders information from cryptocurrency database")
        Component(transactionRepo, "TransactionRepository", "Repository", "Retrieves price information from price database")
        Component(paraswapAdapter, "ParaswapAdapter", "adapter", "Retrieves and manipulates data provided by Paraswap APIs")
        Component(paraswapApi, "ParaswapAPI", "api", "Queries data using Paraswap APIs")
        Component(jupiterAdapter, "JupiterAdapter", "adapter", "Retrieves and manipulates data provided by JupiterAgg APIs")
        Component(jupiterApi, "JupiterAPI", "api", "Queries data using JupiterAgg APIs")
        Component(transactionQueue, "TransactionQueue", "TypeScript: bull", "Stores transactions in Message Queue")
    }
    ComponentDb(cryptoDB, "CryptoDatabase", "PostgreSQL Database", "Cryptocurrency related database")
    Container(queue, "Queue", "JavaScript: NodeJS", "queues jobs and tasks pushed into Redis store")
    SystemDb_Ext(redis, "Redis Store", "Message queue service")
}
System_Ext(notification, "OneSignal", "Push notification service for web and mobile devices")
System_Ext(paraswap, "Paraswap", "On-Chain Request Pool for Quotes")
System_Ext(jupiter, "JupiterAgg", "Swap aggregator on Solana")
Lay_U(swapController, transactionController)
Lay_U(swapService, transactionService)
Rel(mobile, api, "makes API calls", "JSON/HTTPS")
Rel_R(transactionController, transactionService, "uses")
Rel_R(swapController, swapService, "uses")
Rel_U(transactionController, transactionValidator, "uses")
Rel_L(transactionController, authenMiddleware, "uses")
Rel_D(swapController, swapValidator, "uses")
Rel_R(swapService, swapRepo, "uses")
Rel_R(transactionService, transactionRepo, "uses")
Rel_D(swapService, paraswapAdapter, "calls")
Rel_R(paraswapAdapter, paraswapApi, "calls")
Rel_D(paraswapApi, paraswap, "makes API calls")
Rel_D(swapService, jupiterAdapter, "calls")
Rel_R(jupiterAdapter, jupiterApi, "calls")
Rel_D(jupiterApi, jupiter, "makes API calls")
Rel_D(swapService, library, "calls functions")
Rel(queue, library, "calls functions")
Rel(library, blockchain, "retrieves and executes", "rpc")
Rel_U(transactionService, transactionQueue, "pushes transactions")
Rel_R(transactionRepo, cryptoDB, "reads/writes", "ORM: ObjectionJS")
Rel_R(swapRepo, cryptoDB, "reads/writes", "ORM: ObjectionJS")
Rel_R(transactionQueue, redis, "pushes transactions")
Rel_U(queue, redis, "retrieves jobs")
Rel(queue, cryptoDB, "reads/writes", "ORM: ObjectionJS")
Rel_R(queue, notification, "sends messages", "api")
Rel_U(notification, customer, "send notification")
@enduml
